apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcollector
    spec:
      containers:
      - name: otelcol
        args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector
        volumeMounts:
        - mountPath: /conf
          name: collector-config
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: collector-config
        name: collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      probabilistic_sampler:
        hash_seed: 1000
        sampling_percentage: 100

    exporters:
      otlphttp:
        endpoint: "http://jaeger-collector.istio-system:4318"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [probabilistic_sampler]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Service
metadata:
  name: otelcollector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/name: otelcollector
  type: ClusterIP